namespace ProjectAdventure.Enums
{
    public enum ItemType
    {
        WOODEN_SWORD,
        STONE_SWORD,
        STEEL_SWORD,
        WOODEN_BOW,
        STEEL_ARROW,
        WOODEN_CLUB,
        CLUB_WITH_TEETH,
        WOODEN_SHIELD,
        LEATHER_CAP,
        LEATHER_TUNIC,
        LEATHER_PANTS,
        LEATHER_BOOTS,
        BOTTLE,
        WOOL,
        CLOTH,
        WOOD,
        STONE,
        STEEL,
        GOLD,
        TEETH,
        HEALTH_POTION,
        GOLD_COIN,
        SILVER_COIN,
        COPPER_COIN,
        ROTTEN_FLESH,
    }
}
